#define WRITE_TO_FLASH_SIMVOL 0xFFFF //FLA
#define NO_ROOM_ADDRES_SIMVOL 0xFFFE //nor
#define USE_ROOM_ADDRES_SIMVOL 0xFFFD //uro
#define WRITE_ROOM_ADD_TO_FLASH_SIMVOL 0xFFFC //FLr
#define RESET_ROOM_ADDR_SIMVOL 0xFFFB //rrA